export const GET_ALL_SINGERS = "GET_ALL_SINGERS";
export const GET_SINGER_ALBUMS = "GET_SINGER_ALBUMS";
export const GET_ALBUMS_SONGS = "GET_ALBUMS_SONGS";
export const GET_SONGS_COUNT_AMOUNT = "GET_SONGS_COUNT_AMOUNT";
export const CLEAR_STEPPER = "CLEAR_STEPPER";